[workspace]
members = [
  "crates/rift-core",
  "crates/rift-discovery",
  "crates/rift-mesh",
  "crates/rift-media",
  "crates/rift-protocol",
  "crates/rift-nat",
  "crates/rift-rndzv",
  "crates/rift-sdk",
  "crates/rift-dht",
  "crates/rift-metrics",
  "crates/rift-e2e",
  "crates/rndzv-sim",
  "bin/rift",
  "crates/rift-wasm",
  "crates/rift-web-chat",
  "crates/rift-torrent",
  "bin/rift-ws-relay",
]
resolver = "2"
